---
# Steps to be executed on the coordinator node (configure citus)

- name: Provision all hosts
  become: true
  become_user: postgres
  become_method: su
  tags: [psql, coordinator, configure_citus]
  block:
    - name: Set coordinator host
      postgresql_query:
        db: "{{ pg_database }}"
        query: "SELECT citus_set_coordinator_host('servers-db-1', 5432);"
    - name: Set worker nodes
      postgresql_query:
        db: "{{ pg_database }}"
        query: "SELECT * from citus_add_node('{{ item }}', 5432);"
        login_user: postgres
        login_password: "{{ pg_postgres_password }}"
      loop:
        - servers-db_slave1-1
        - servers-db_slave2-1
        - servers-db_slave3-1
    - name: Get all active worker nodes
      postgresql_query:
        db: "{{ pg_database }}"
        query: "SELECT * FROM citus_get_active_worker_nodes();"
        register: worker_nodes
    - name: Print all active worker nodes 
      debug: 
        var: worker_nodes
