---

- name: Fetch Kong deb-package
  ansible.builtin.get_url:
    url: "{{ kong_url }}{{ kong_package_name }}"
    dest: /tmp/kong.deb

- name: Install deb-package
  ansible.builtin.apt:
    deb: /tmp/kong.deb
