---
# Create kong service and kong route 

- name: Wait for open admin port
  wait_for:
    host: "{{ http_kong_host }}"
    port: "{{ http_admin_listen }}"
    state: started
    timeout: 60

- name: Create kong service
  uri:
    url: "http://{{ http_kong_host }}:{{ http_admin_listen }}/services"
    method: POST
    body_format: form-urlencoded
    body:
      name: example_service
      url: "http://ifconfig.me"
  changed_when: service.status == 201
  failed_when: not service.status in [409, 201]
  register: service

- name: Create kong route
  uri:
    url: "http://{{ http_kong_host }}:{{ http_admin_listen }}/services/{{ service.json.name if service.changed else service.json.fields.name }}/routes"
    method: POST
    body_format: form-urlencoded
    body:
      name: example_route
      paths:
        - /
  changed_when: route.status == 201
  failed_when: not route.status in [409, 201]
  register: route

