---
# Install and Configure Kong

- name: Change ulimit for Kong
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: 4096
  tags: [kong]

- name: Install Kong
  import_tasks: installation.yml
  tags: [kong, install_kong]

- name: Create kong entities
  import_tasks: kong_entities.yml
  tags: [kong, entities_kong]

