---

- name: Include host related variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Install python-apt against Debian-based hosts
  ansible.builtin.apt:
    name: python-apt
    state: present
    update_cache: yes
  when: ansible_os_family | lower == 'debian'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Kong for current OS if it's not installed yet
  ansible.builtin.include_tasks: 'install/{{ ansible_os_family | lower }}.yml'
  when: "not 'kong' in ansible_facts.packages"

- name: Check if perform_actions is defined and if so change kong configuration
  ansible.builtin.include_tasks: 'entity/{{ action }}/{{ database }}.yml'
  when: perform_actions is defined
  vars:
    action: "{{ item.action }}"
    kong_entity: "{{ item.kong_entity }}"
    entity_name: "{{ item.entity_name }}"
    entity_params: "{{ item.entity_params }}"
  loop: "{{ perform_actions }}"

- name: Reload Kong
  ansible.builtin.service:
    name: kong
    state: reloaded
  when: "database == 'off'"

