---
# Install mongodb master node

- name: Change ulimit to 64000
  pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: nofile
    value: 64000
  tags: [mongo]

- name: Install mongod
  import_tasks: mongod.yml
  tags: [mongo, install_mongod]

- name: Install mongosh
  import_tasks: mongosh.yml
  tags: [mongo, install_mongosh]

