---
# Install MongoD using .tgz and Start the daemon

- name: Install dependencies
  apt:
    name: 
      - libcurl4
      - openssl
      - liblzma5
    state: present
    update_cache: yes

- name: Copy init.d service file to manage mongod-service
  template:
    src: mongod.service.j2
    dest: /etc/init.d/mongod
    mode: a+x
  notify: start mongo

- name: Fetch and unarchive mongod tarball
  unarchive:
    src: "https://fastdl.mongodb.org/linux/{{ mongodb_version }}.tgz"
    dest: /tmp
    remote_src: yes
  notify: start mongo

- name: Get all mongo related binaries
  find:
    path: "/tmp/{{ mongodb_version }}/bin"
  register: mongo_binaries

- name: Create symlinks for all binaries in /usr/local/bin
  file:
    name: "/usr/local/bin/{{ item.path | basename }}" 
    src: "{{ item.path }}"
    state: link 
  loop: "{{ mongo_binaries.files }}"

- name: Create necessary directories for mongod
  file:
    name: "{{ item }}"
    state: directory
    force: yes
  loop:
    - /var/lib/mongo
    - /var/log/mongodb

