---

- name: "Add entities {{ kong_entity }}"
  ansible.builtin.blockinfile:
    path: "{{ declarative_config }}"
    marker: "# {{ kong_entity }} {mark}"
    insertafter: "^{{ kong_entity }}:"
    block: "{% for item in entity_params -%} - {{ item | to_nice_yaml(indent=2) | indent(2) }} {%- endfor %}"

