---
# Install PostgreSQL 

- name: Install dependencies
  apt:
    name: 
      - gnupg
      - pip
      - libpq-dev
      - gcc
    state: present
    update_cache: yes

- name: Install psycopg2 to manage PostgreSQL
  pip:
    name: psycopg2
    state: present

- name: Add PostgreSQL apt_key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL apt_repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ version_ubuntu }}-pgdg main"
    state: present

- name: Install PostgeSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  notify: restart psql

- name: Update postgresql.conf
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: "^#listen_addresses"
    line: "listen_addresses = '*'"
  notify: restart psql

- name: Update pg_hba.conf
  lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+scram-sha-256$'
    line: "host all all 0.0.0.0/0 md5"
  notify: restart psql

- name: Flush handlers
  meta: flush_handlers

