---
# Install and Configure PostgreSQL for Kong

- name: Install PostgreSQL
  import_tasks: installation.yml
  tags: [psql, install_psql]

- name: Create user and database for kong in PostgreSQL
  import_tasks: kong.yml
  tags: [psql, kong_psql]
