---
# Install and set up PSQL

- name: Install necessary requirements
  apt:
    name: 
      - gnupg
      - pip
      - libpq-dev
      - gcc
    state: present
    update_cache: yes
  tags: [psql, install_psql]

- name: Add apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags: [psql, install_psql]

- name: Add apt package
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ version_ubuntu }}-pgdg main"
    filename: pgdg
    state: present
  tags: [psql, install_psql]

- name: Install PostgeSQL
  apt:
    update_cache: yes
    name: postgresql
    state: present
  tags: [psql, install_psql]

- name: Install psycopg2 to manage psql 
  pip:
    name: psycopg2
    state: present
  tags: [psql, install_psql]

- name: Update PostgreSQL Configuration Files
  notify: start psql
  tags: [psql, config_psql]
  block:
    - name: Update postgresql.conf
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: "^#listen_addresses"
        line: "listen_addresses = '*'"
    - name: Update pg_hba.conf
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+scram-sha-256$'
        line: "host all all 0.0.0.0/0 md5"

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
  tags: [psql, config_psql]

- name: Setting up PSQL under postgres user
  become: true
  become_user: postgres
  become_method: su
  tags: [psql, db_user_psql]
  block:
    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ pg_user }}"
        password: "{{ pg_password }}"

    - name: Create PostgreSQL database
      postgresql_db:
        name: "{{ pg_database }}"
        owner: "{{ pg_user }}"

- name: Check whether citus installed or not
  command: dpkg-query -W postgresql-15-citus-11.3
  changed_when: citus.rc == 1
  failed_when: citus.rc > 1
  register: citus
  tags: [psql, install_citus]

- name: Download script (citus extension for PostgreSQL)
  get_url:
    url: https://install.citusdata.com/community/deb.sh 
    dest: /tmp/add-citus-repo.sh
    mode: a+x
  when: citus.changed
  tags: [psql, install_citus]

- name: Run script that add new citus apt package
  command: /tmp/add-citus-repo.sh 
  when: citus.changed
  tags: [psql, install_citus]

- name: Install citus extension
  apt:
    name: postgresql-15-citus-11.3
    state: present
  when: citus.changed
  tags: [psql, install_citus]

- name: Add shared_preload_libraries to postgresql.conf
  lineinfile:
    path: /etc/postgresql/15/main/postgresql.conf
    regexp: '^#shared_preload_libraries'
    line: "shared_preload_libraries = 'citus'"
  notify: restart psql
  tags: [psql, configure_citus]
  
