---

- name: "Remove entity {{ kong_entity }} with name {{ entity_name }}"
  ansible.builtin.blockinfile:
    path: "{{ declarative_config }}"
    marker: "# {{ kong_entity }} {{ entity_name }} {mark}"
    state: absent
